FROM alpine:3.18.2 as builder
LABEL maintainer="mbober1@gmail.com"
RUN apk update 
RUN apk add libusb-dev git cmake make gcc g++ linux-headers udev

# Build rtl-sdr
WORKDIR /
COPY rtl-sdr rtl-sdr
RUN mkdir rtl-sdr/build && cd rtl-sdr/build && cmake ../ -DINSTALL_UDEV_RULES=ON && make -j`nproc` && make install
# RUN echo 'blacklist dvb_usb_rtl28xxu' > /etc/modprobe.d/blacklist-rtl.conf

# Build rtl-wmbus
WORKDIR /
COPY rtl-wmbus rtl-wmbus
RUN cd rtl-wmbus && make release && make install

# Build wmbusmeters
WORKDIR /
COPY wmbusmeters wmbusmeters
RUN cd wmbusmeters && ./configure
# RUN make -j`nproc`
# RUN make install